# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cfa412b25b30bfd715bc71bbb3eefceb7af69bd27834431607673233e674bb83c673663f0ed14ce5f6bf8913786049c26566c0c69112c5be3a7613344000cae

test:
  secret_key_base: 711f32e7f6e6a33763097c88d1b3e9e3848f302d4b206d35d4d6f44061bed324bd99f0bf67376f5b294e77f8c8d048de0d0d9cf39f26d70f2afae35826cfa318

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
